#!/bin/bash

DEST='/Volumes/SNS'

echo credentials backup
rsync -avzh  ~/Documents/credentials/* $DEST/backups/credentials/

echo documents backup
rsync -avzh  ~/Documents/solo-tiger $DEST/backups/Documents/solo-tiger
rsync -avzh  ~/Documents/JCI $DEST/backups/Documents/JCI
rsync -avzh  ~/Pictures $DEST/backups/Documents/Pictures

echo git backup
cd ~/workspace/nlp-research
ssh-agent bash -c "ssh-add ~/.ssh/michaeldata;git push $DEST/backups/git/nlp-research HEAD"

