#!/usr/bin/python3
import sys

print("testing opencv in python3")

try:
    import cv2
    print("It works! Using OpenCV version {}".format(cv2.__version__))
except Error as e:
    print("Doesn't work!")
    print("Unexpected error:", sys.exc_info()[0])
    raise
