#!/usr/bin/python3
import sys

print("testing keras in python3")

try:
    from keras import backend as K
    print('It works!')
except Error as e:
    print("Doesn't work!")
    print "Unexpected error:", sys.exc_info()[0]
    raise
