#!/usr/bin/python3
import sys

print("testing tensorflow in python3")

try:
    import tensorflow as tf
    hello = tf.constant("It works! Using version {}".format(tf.__version__))
    sess = tf.Session()
    print(sess.run(hello))
except:
    print("Doesn't work!")
    print("Unexpected error:", sys.exc_info()[0])
    raise
