#!/bin/bash

DEST=$1

echo "Backing up to $1"

if [[ "$2" = "--delete" ]]
then
    echo "Deleting old backups"
    DEL='--delete'
else
    echo "Not deleting old backups"
    DEL=''
fi

echo credentials backup
rsync $DEL -acvzh ~/.ssh/ $DEST/backups/credentials

echo documents backup
rsync $DEL -acvzh ~/Pictures/ $DEST/backups/Documents/Pictures

echo
echo git backup
cd ~/workspace/nlp-research
ssh-agent bash -c "ssh-add ~/.ssh/michaeldata;git push $DEST/backups/git/nlp-research HEAD"

cd ~/.password-store
ssh-agent bash -c "ssh-add ~/.ssh/michaeldata;git push $DEST/backups/git/password-store HEAD"
