#!/bin/bash

DEST='/Volumes/Michael500'

echo documents backup
rsync -avzh --delete ~/Documents/JCI/ $DEST/backups/JCI

echo media backup
rsync -avzh --delete ~/Media/ $DEST/backups/Media
rsync -avzh --delete ~/Pictures/ $DEST/backups/Pictures

